### ISSUE TITLE
要测回程路由应该选择哪个软件最好

### ISSUE THREAD

**Issue by renoustfall** [chika0801/tool#1]
一直不是很懂 besttrace nexttrace mtr 这三个有什么区别，测出来结果都不一样，不知道要以哪个为准 求解答
谢谢

**Comment by chika0801** [comment]
我用得最多是besttrace，现在个人用，基本遇到不超过正常使用次数限制（以前有）
他能测ICMP和TCP PING

nexttrace出时，是因为那时有人吐槽besttrace有每天使用次数限制。它现在比上面的besttrace有一个功能是测UDP回程。besttrace测不了UDP回程。

mtr 我不是专业的，看结果也分析不出来回程链路哪跳怎么样丢包怎样。我主要拿它看看TCP UDP PING，发大包时的路由和besttrace，nexttrace测的一样不。
